name: Update CF Problems

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-cf-problems:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.92.2"
          extended: true

      - name: Build
        run: |
          git config core.quotePath false
          hugo

      - name: Install requirements
        run: pip install requests

      - run: python scripts/UpdateCF_Problems.py

      - name: copy json
        run: cp public/contests.json static/contests.json

      - name: Commit
        run: |
          git status
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git diff --quiet && git diff --staged --quiet || git commit -am "chore: update CF Problems"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}


      - name: Build
        run: |
          git config core.quotePath false
          hugo --minify
      - name: Check links
        id: check-links
        uses: peter-evans/link-checker@v1
        with:
          args: -r public -d public -x "https?:\/\/"

      - name: Fail on link errors
        run: exit ${{ steps.check-links.outputs.exit_code }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: tom0727/tom0727.github.io
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: publish
          commit_message: ${{ github.event.head_commit.message }}
